WITH Combined_Orders AS (
    SELECT 
        F.FLAVOR,
        COALESCE(F.TOTAL_ORDER, 0) AS FIRST_HALF_ORDER,
        COALESCE(SUM(J.TOTAL_ORDER), 0) AS JULY_ORDER
    FROM 
        FIRST_HALF F
    LEFT JOIN 
        JULY J ON F.FLAVOR = J.FLAVOR
    GROUP BY 
        F.FLAVOR
)
SELECT 
    FLAVOR
FROM 
    Combined_Orders
ORDER BY 
    (FIRST_HALF_ORDER + JULY_ORDER) DESC
LIMIT 3;
